name: Auto Update BDTV Playlist

on:
  schedule:
    - cron: "0 */2 * * *"   # প্রতি ২ ঘণ্টা পর
  workflow_dispatch:


permissions:
  contents: write


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Install Requirements
        run: |
          pip install requests


      - name: Run BTV Generator
        run: |
          python bd.py


      - name: Check Output
        run: |
          ls -la
          echo "----- bdt.m3u8 -----"
          cat bdt.m3u8


      - name: Commit Updated Playlist
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add bdt.m3u8

          git commit -m "Auto update bdt.m3u8" || echo "No changes"

          git push
